### ISSUE TITLE
Question about randomly-generated faces

### ISSUE THREAD

**Issue by sky-fly97** [browatbn2/3FabRec#15]
Hello,  I have learned a lot from reading your paper. It is an excellent job. However, I met some problems in the process of reading the paper. I hope you can help me.
1、How is Fig. 3 and Fig.4 generated? I find it is not stated more in the paper. I would like to know more about it.
2、Since it is possible to generate many different poses or styles from the original input image, can these images be used as additional data augmentation to train other supervised models ？
Thanks！

**Comment by sky-fly97** [comment]
> Hi, thank you, I'm happy to help:
> 
> 1. We generate Fig.3 by skipping the encoder and just decode a randomly sampled latent vector. Fig 4. is generated in a similar way, but instead of a random vector we interpolate between 2 vectors from encoded images. So the leftmost and rightmost faces in Fig. 4 are reconstructions of input images and all faces in-between are generated from their interpolated embeddings.
> 2. Yes, in theory that should be possible. In fact, there are approaches that do this in some form... Here for example for style:
>    https://arxiv.org/abs/1908.06440
>    However, there is currently no way of controlling pose/style independently from shape (i.e. landmarks). You could take the generated landmarks (like for example in Fig. 4) as ground truth training inputs, but I'm not sure if this would give you any benefit.
> 
> I did some work on disentanglement (as did other people) a while ago:
> https://github.com/browatbn2/MAD
> 
> I was planning to combine the two but I never actually got around to do it.
> If you're curious, please feel free to try out! :)

Thanks! I'm sorry to see it now. 
The inconsistency of manual data annotation is a big problem, which leads to the different prediction results of the model for the front and rear frames of video, resulting in the problem of ldmk jitter. At present, I am committed to the ldmk jitter of the small model and try different methods to improve it. Maybe I can try this data augmentation method.

**Comment by sky-fly97** [comment]
> Hi, thank you, I'm happy to help:
> 
> 1. We generate Fig.3 by skipping the encoder and just decode a randomly sampled latent vector. Fig 4. is generated in a similar way, but instead of a random vector we interpolate between 2 vectors from encoded images. So the leftmost and rightmost faces in Fig. 4 are reconstructions of input images and all faces in-between are generated from their interpolated embeddings.
> 2. Yes, in theory that should be possible. In fact, there are approaches that do this in some form... Here for example for style:
>    https://arxiv.org/abs/1908.06440
>    However, there is currently no way of controlling pose/style independently from shape (i.e. landmarks). You could take the generated landmarks (like for example in Fig. 4) as ground truth training inputs, but I'm not sure if this would give you any benefit.
> 
> I did some work on disentanglement (as did other people) a while ago:
> https://github.com/browatbn2/MAD
> 
> I was planning to combine the two but I never actually got around to do it.
> If you're curious, please feel free to try out! :)

Sorry to bother you again. Are the left and right pictures you mentioned here given at the beginning? Can I generate such continuous data if I only have an angle input picture？
`So the leftmost and rightmost faces in Fig. 4 are reconstructions of input images`

**Comment by browatbn2** [comment]
Yes, left and right are given. 

> Can I generate such continuous data if I only have an angle input picture?
You mean, if you only have 1 image instead of 2? No, I don't think so, not in the current version, unfortunately.
However, you don't necessarily need 2 images at the 'end' poses. Instead of doing interpolation between endpoints, you could also extrapolate from 2 subsequent images/poses.
