### ISSUE TITLE
Using pretrained model

### ISSUE THREAD

**Issue by vinayb1012** [browatbn2/3FabRec#16]
Hi, I am trying to use the provided model trained on 300w on a sample unseen image. However I am getting some artifacts in the reconstructions and as a result the predicted landmarks are also random.

![image](https://user-images.githubusercontent.com/52788864/132375462-150cb07d-fcdf-46c2-b15f-d43a128e9b97.png)

![image](https://user-images.githubusercontent.com/52788864/132375255-56914757-24b8-4d81-bbd7-d53f1d442eee.png)

Here is what I did: 

* Face cropped the image
* Resized to (256, 256)
* Normalized between (0,1) and (-1, 1) with the same result

Am I missing anything here?

**Comment by browatbn2** [comment]
Hi! Hm, did you set the model to eval?

**Comment by vinayb1012** [comment]
Hi. Yes, I did set it to eval.
