### ISSUE TITLE
There's no eval_aae_landmarks.py in the package.

### ISSUE THREAD

**Issue by jingchunhui** [browatbn2/3FabRec#22]
Hi, excuse me.
I didn't find eval_aae_landmarks.py in the package.

**Comment by jingchunhui** [comment]
So,I think the eval_aae_landmarks.py and the eval_landmarks.py in README's “Visualize results” and "Benchmark performance" parts are the same file(eval_landmarks.py), am i right?

**Comment by browatbn2** [comment]
Oh, yes, sorry, that must be a typo in the readme.

**Comment by jingchunhui** [comment]
OK, thank you very much!
