### ISSUE TITLE
Aflw annotations

### ISSUE THREAD

**Issue by MartFire** [browatbn2/3FabRec#25]
Hi, I have some questions about AFLW annotations.

In the AFLW dataset code, you merge old and new annotations. Is the only reason to keep the "yaw, pitch, roll" keys? These keys are not used anywhere else in the code so is this operation necessary?

Also, after the merge 10 annotations are missing, the training dataset has 19993 annotations instead of 20000, and the test dataset has 4383 instead of 4886. Did you encounter this issue?

**Comment by browatbn2** [comment]
Ah, that's probably because I was using "yaw, pitch, roll" in a different project. I guess it's not necessary in this project.

Yes, I remember the issue with the slightly different dataset sizes. If I remember correctly, a few images from AFLW were removed in a later version of the dataset.
