### ISSUE TITLE
Bug while using Pytorch 1.5

### ISSUE THREAD

**Issue by aseembits93** [browatbn2/3FabRec#3]
Hi @browatbn2 ! Thanks for sharing your work. I was trying to reproduce your results by training the autoencoder.
I get this error when I run `python train_aae_unsupervised.py --sessionname my_model --daug 4 --input-size 256 --epoch 1 `

> Traceback (most recent call last):
  File "train_aae_unsupervised.py", line 462, in <module>
    run(args)
  File "train_aae_unsupervised.py", line 403, in run
    fntr.train(num_epochs=args.epochs)
  File "train_aae_unsupervised.py", line 171, in train
    self._run_epoch(self.datasets[TRAIN])
  File "train_aae_unsupervised.py", line 214, in _run_epoch
    self._run_batch(data, eval=eval)
  File "train_aae_unsupervised.py", line 304, in _run_batch
    loss.backward()
  File "/home/aseem/anaconda3/envs/myenv/lib/python3.8/site-packages/torch/tensor.py", line 198, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/aseem/anaconda3/envs/myenv/lib/python3.8/site-packages/torch/autograd/__init__.py", line 98, in backward
    Variable._execution_engine.run_backward(
**RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [512, 99]], which is output 0 of TBackward, is at version 2; expected version 1 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).**

I understand that pytorch==1.1 has been tested for this version. Due to mismatch with CUDA versions and latest hardware (V100 doesn't support CUDA 10.0 while pytorch 1.1 requires cuda 10.0), I am unable to install pytorch 1.1. Please let me know if you could help out with the error. Best Regards,

**Comment by aseembits93** [comment]
For now, I have downgraded my pytorch to 1.1. I'll try to solve the trouble in my free time.

**Comment by browatbn2** [comment]
Hi, thanks for letting me know about this. Looks like it's time for me to update torch and cuda... :) 
I'll fix this soon.

**Comment by ZYzhouya** [comment]
> Hi, thanks for letting me know about this. Looks like it's time for me to update torch and cuda... :)
> I'll fix this soon.

Excuse me. 
I meet the same issue:

_RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [512, 99]], which is output 0 of TBackward, is at version 4; expected version 3 instead. Hint: the backtrace further above shows the operation that failed to compute its gradient. The variable in question was changed in there or anywhere later. Good luck!_

Have you solved it? My pytorch version is 1.6.0.

**Comment by browatbn2** [comment]
Hm, I thought I fixed it a while ago... but I guess I did not :confused:

**Comment by ZYzhouya** [comment]
> Hm, I thought I fixed it a while ago... but I guess I did not 😕

Thanks for your reply！
I cloned the old version code, so I still meet the issue. I just fixed the error following your git log. Now it's ok. 👍

**Comment by browatbn2** [comment]
Ok, good to hear! :)
