### ISSUE TITLE
Training for arbitrary number of landmarks

### ISSUE THREAD

**Issue by aseembits93** [browatbn2/3FabRec#4]
Hi @browatbn2 

Hope all's well with you!

I have successfully trained and tested the existing pipeline of your work. I am quite excited about using it in my context. I have my own internal dataset with images having 38 landmarks on the face. I'm trying to modify your code to make it work. So far, I have prepared the annotation files in the exact format WFLW demands, and have copied and modified the wflw.py code for the specific number of landmarks. I can save the crops but as soon as training starts, the file 'landmarks/lmutils.py' throws errors. After closer inspection, I noticed that the number 68 is hardcoded at multiple places in lmutils.py.
Really hope if you could guide me with the necessary modifications! Thanks and Take Care!

**Comment by browatbn2** [comment]
Hi, @aseembits93 thanks for your interest in the code! I'm happy to help. Yes, the number of landmarks is hardcoded right now. I was only expecting 21,68,or 98 landmarks. For horizontal flips, for example, it matters which face parts the landmarks correspond to.
It's not difficult to add other formats though. Do you have some kind of chart showing where your 40 landmarks are? I can add it quickly on Monday :)

**Comment by aseembits93** [comment]
Thanks for the quick reply! :) Let me get back to you on Monday. Now that I think of it, a quick solution for me could be to just use the 21 points which correspond to the AFLW dataset (if i'm not wrong). That's a quick way to go about it. I totally get you about the flipping part. it's really confusing because points need to interchanged. Enjoy the weekend. :)
Best Regards,

**Comment by aseembits93** [comment]
Hi @browatbn2 , Here's my quick and dirty diagram of the face with 38 points (0-37) labelled 
![landmarksscheme](https://user-images.githubusercontent.com/4725571/88046018-06e3c980-cb82-11ea-9a29-5dec566fc621.png)

Notice that there are no points on the chin and jaw, unlike all the existing datasets you have used (AFLW, 300-W, WFLW). Currently, I have formatted my annotations in the style of WFLW. Let me know the next steps. Have a good day! Thanks!

Best Regards,

**Comment by browatbn2** [comment]
Hey, sorry for the delay, busy with a paper deadline...
Great, thanks for the diagram! I just pushed some small changes, it might just work now with 38 landmarks. Have a look at csl_common/utils/transforms.py:371, that's for flipping faces. See if that makes sense to you. 

Give it a try but there might be other places that need to be updated as well that I forgot.

**Comment by aseembits93** [comment]
Dear @browatbn2 
Thanks for the help. I'm onto it. Hope your paper deadline went well.
Let me get back as soon as possible if I face any trouble! Take care.

**Comment by aseembits93** [comment]
Dear @browatbn2 

I think I have some understanding of the problem I'm facing. I'll try to describe it as clearly as possible.

Line 269 of train_aae_landmarks.py leads me to heatmaps_to_landmarks() in Line 57 of fabrec.py. Since the heatmap dimension 1 is 38 (not in [19, 68, 98]), decode_heatmaps() at Line 155 from lmutils.py is called. 'enc_layer_ids' at Line 159 has a shape of (45,). This is problematic as Line 163 at lmutils.py is doing 'layer = hms[i]' but since hms has only length of 38, the index i goes out of range. I was trying to understand how the number 45 came for the shape of enc_layer_ids but got lost there. 

Hope to hear back soon from you regarding this.

Best,

**Comment by browatbn2** [comment]
Ah, right, I forgot that part. I just updated the code.

**Comment by aseembits93** [comment]
Hi @browatbn2 
The latest update from my side is that I'm able to run the training pipeline with one minor addition of the ocular distance calculation for 38 point landmarks. I think the visualize_batch() function requires some modification, I've simply commented out that function. I'll try to modify the visualize_batch function in the meanwhile.  
Thanks a lot really for your help. 
Best,

**Comment by browatbn2** [comment]
Great! :)

Regarding the visualization, I might have an idea what the issue was. I pushed another quick update. 

Also, if you'd like to show landmarks as wireframes, you'd have to add a line to vis.py:303-308 and add another draw_wireframe_lines method.

**Comment by aseembits93** [comment]
Awesome! I can visualize with ease. With just a single training epoch, I'm able to get really good results! thanks really for sharing and helping out with the code :)
