### ISSUE TITLE
Is there a pre-trained model?

### ISSUE THREAD

**Issue by Xiaocong6** [browatbn2/3FabRec#5]
hi~thanks for your work. I am very interested in it.
I want to run the demo, can you provide the trained model?
Thank you a lot!!!

**Comment by Xiaocong6** [comment]
sorry, i find the script. (orz)

**Comment by browatbn2** [comment]
Ah ok, great, I was just about to write :). Let me know in case there are any issues with it.

**Comment by Xiaocong6** [comment]
Haha, so kind of you!
