### ISSUE TITLE
AttributeError: module 'os' has no attribute 'uname'

### ISSUE THREAD

**Issue by TristaZhang** [browatbn2/3FabRec#9]
“AttributeError: module 'os' has no attribute 'uname'” when running train_aae_landmarks.py，why？Thanks~

**Comment by browatbn2** [comment]
It seems to be a Windows or Python2.7 issue. I just pushed a fix. Should work now.

**Comment by TristaZhang** [comment]
> It seems to be a Windows or Python2.7 issue. I just pushed a fix. Should work now.

Thanks a lot~
